In [67]:
import pandas as pd

In [68]:
doc = pd.read_excel('CUENTAS_FUN_SOCIEDADES.xlsx', None)

In [69]:
DF = doc['CUENTAS']

In [73]:
DF.loc[DF['Nivel 3'] == DF['Nivel 3'][0]]

,Cuenta,Nivel 2,Nivel 3,Nivel 4,Nivel 5,Descripción,ADM PLANFIN,P&L,Excepción,P&L 2,...,PRECARGADAS FUNCIÓN,EXCEPCIONES,CUENTA POR INDICE y DESCONTINUADA,CUENTAS PRESTACIONES,AF CLASES,AF NÚMERO,AF HISTÓRICO,POSPRE,COMENTARIO,Tabla de tolerancia
0,40000000,UTILBRUTA ** UTILIDAD BRUTA **,VENTAS TOTAL VENTAS NETAS,VTASCONTAD VENTAS CONTADO,VTACONTAD VENTAS CONTADO,Ventas,VENTAS NO PPTO,Ventas Netas,NaN,NaN,...,NaN,NaN,CLASE AF,NaN,TERRENOS,1000.0,NaN,0,NaN,NaN
1,40000001,UTILBRUTA ** UTILIDAD BRUTA **,VENTAS TOTAL VENTAS NETAS,VTASCONTAD VENTAS CONTADO,VTACONTAD VENTAS CONTADO,Ventas Contado Exent,VENTAS NO PPTO,Ventas Netas,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40000003,NaN,NaN
2,40000002,UTILBRUTA ** UTILIDAD BRUTA **,VENTAS TOTAL VENTAS NETAS,VTASCONTAD VENTAS CONTADO,VTACONTAD VENTAS CONTADO,Vtas. Contado 0%,VENTAS NO PPTO,Ventas Netas,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40000003,NaN,NaN
3,40000003,UTILBRUTA ** UTILIDAD BRUTA **,VENTAS TOTAL VENTAS NETAS,VTASCONTAD VENTAS CONTADO,VTACONTAD VENTAS CONTADO,Vtas. Contado Grav.,VENTAS,Ventas Netas,NaN,NaN,...,NaN,RESTYSFERA,CUENTAS POR INDICES,NaN,NaN,NaN,NaN,40000003,Restaurante y Sferas cargan sus ventas,NaN
4,40000004,UTILBRUTA ** UTILIDAD BRUTA **,VENTAS TOTAL VENTAS NETAS,VTASCONTAD VENTAS CONTADO,VTACONTAD VENTAS CONTADO,Vtas. Contado 10%,VENTAS NO PPTO,Ventas Netas,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40000003,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,40400001,UTILBRUTA ** UTILIDAD BRUTA **,VENTAS TOTAL VENTAS NETAS,VTASCONTAD VENTAS CONTADO,DEVCONTAD .BONIF Y DEVOLUC CONTADO,Bonificaciones Cupones Promocion Exenta,VENTAS,Ventas Netas,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40400001,NaN,NaN
57,40400002,UTILBRUTA ** UTILIDAD BRUTA **,VENTAS TOTAL VENTAS NETAS,VTASCONTAD VENTAS CONTADO,DEVCONTAD .BONIF Y DEVOLUC CONTADO,Bonificaciones Cupones Promocion 0%,VENTAS NO PPTO,Ventas Netas,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40400001,NaN,NaN
58,40400003,UTILBRUTA ** UTILIDAD BRUTA **,VENTAS TOTAL VENTAS NETAS,VTASCONTAD VENTAS CONTADO,DEVCONTAD .BONIF Y DEVOLUC CONTADO,Bonificaciones Cupones Promocion 16%,VENTAS NO PPTO,Ventas Netas,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40400001,NaN,NaN
59,40400004,UTILBRUTA ** UTILIDAD BRUTA **,VENTAS TOTAL VENTAS NETAS,VTASCONTAD VENTAS CONTADO,DEVCONTAD .BONIF Y DEVOLUC CONTADO,Bonificaciones Cupones Promocion 11,VENTAS NO PPTO,Ventas Netas,NaN,NaN,...,NaN,NaN,DESCONTINUADA,NaN,NaN,NaN,NaN,40400001,NaN,NaN
61,40400006,UTILBRUTA ** UTILIDAD BRUTA **,VENTAS TOTAL VENTAS NETAS,VTASCONTAD VENTAS CONTADO,DEVCONTAD .BONIF Y DEVOLUC CONTADO,BONIF CUPONES PROMOCION 8%,VENTAS NO PPTO,Ventas Netas,NaN,NaN,...,NaN,NaN,CLASE AF,NaN,MANIQUIES,20000.0,51000255.0,0,NaN,NaN

In [ ]:
doc['Nivel 3'][0]

In [ ]:
doc['CUENTAS']

In [ ]:
type( pd.read_excel('CUENTAS_FUN_SOCIEDADES.xlsx', None)  )

In [ ]:
"4000"==str(4000)

In [81]:
{"A":"a"}.keys()

dict_keys(['A'])

In [83]:
for i in doc.keys():
    print(i)

CUENTAS
Sheet1
FUN
Sociedades
JERQ_Cuentas

In [84]:
doc = pd.read_excel('CUENTAS_FUN_SOCIEDADES.xlsx', None)

In [88]:
type(doc['CUENTAS'])

pandas.core.frame.DataFrame